name: Build and Attach pathetic-example jar to release

on:
  release:
    types: [published]

jobs:
  build-and-release:
    name: Build and Attach
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: mvn clean install -B -DskipTests

      - name: Upload Example artifact
        uses: actions/upload-artifact@v4
        with:
          name: example
          path: example/target/pathetic-example.jar

      - name: Attach jar to release
        uses: softprops/action-gh-release@v2
        with:
          files: example/target/pathetic-example.jar
